### ISSUE TITLE
failed installing 

### ISSUE THREAD

**Issue by yulrizka** [golang/lint#194]
Failed to compile with go1.6
```
➜ go get -u github.com/golang/lint/golint  
# github.com/golang/lint
../src/github.com/golang/lint/lint.go:1492: too many arguments in call to types.Eval
../src/github.com/golang/lint/lint.go:1492: assignment count mismatch: 2 = 3
```

**Comment by yulrizka** [comment]
Apparently I had an outdated version of `$GOPATH/src/golang.org/x/tools` removing it and installing it again fixed the problem
