### ISSUE TITLE
Master doesn't build anymore: undefined: types.NewInterface2

### ISSUE THREAD

**Issue by Soulou** [golang/lint#402]
```
└> go get -u golang.org/x/lint/golint
# golang.org/x/tools/go/internal/gcimporter
Projects/Go/src/golang.org/x/tools/go/internal/gcimporter/bimport.go:541:8: undefined: types.NewInterface2
Projects/Go/src/golang.org/x/tools/go/internal/gcimporter/iimport.go:540:10: undefined: types.NewInterface2
```

**Comment by sosiska** [comment]
any workaround?

**Comment by JackBracken** [comment]
+1

Seeing failed builds in https://github.com/prudhvitella/terraform-provider-infoblox/pull/32

Verified it fails on my local machine also.

**Comment by Tkanos** [comment]
the same when you run the command 
```bash
go get -u golang.org/x/lint/golint                                                                         2 ↵  7610  12:05:05 
# golang.org/x/tools/go/internal/gcimporter
../../golang.org/x/tools/go/internal/gcimporter/bimport.go:541:8: undefined: types.NewInterface2
../../golang.org/x/tools/go/internal/gcimporter/iimport.go:540:10: undefined: types.NewInterface2
```

**Comment by lowzj** [comment]
same problem. It seems that the source `bimport.go` was changed on 2018-06-12 22:33:41.
```
9a70f1fcb go/internal/gcimporter/bimport.go (Robert Griesemer     2018-06-12 22:33:41 -0700  541)               t := types.NewInterface2(p.methodList(parent, tname), embeddeds)
```

**Comment by slawo** [comment]
all projects with go get -u github.com/golang/lint/golint in CI are now bust

**Comment by zjshen14** [comment]
Any ETA on this? It blocks all our CI jobs.

**Comment by andybons** [comment]
Looking into this.

**Comment by andybons** [comment]
@griesemer is working on a fix as we speak.

**Comment by griesemer** [comment]
All: sorry about this. On it.

**Comment by griesemer** [comment]
Well, I missed a few more places. One more CL to come.

**Comment by griesemer** [comment]
There's one more CL pending for review but it's only affecting tests. Please let me know if

go get -u golang.org/x/lint/golint

still doesn't work for non 1.11 builds.

**Comment by msound** [comment]
We are using Travis CI and go 1.9.7, the build is now successful and `go get -u golang.org/x/lint/golint` is working fine now.

**Comment by griesemer** [comment]
Post-mortem: Late last night (with emphasis on "late") I created a larger CL in an attempt to finally update x/tools with all the latest fixes and changes that we've made to the various importers in the std lib. This also included fixes to go/types and new tests. The CL was approved and passed all (1.11) tests and I submitted it somewhat in a rush this morning while running out of the door, not thinking abut pre-1.11 builds. As we all saw, the non-1.11 builds failed quickly, and with it tools such as lint that depend on go/types. It was "obvious" what needed to be fixed (the go/types.NewInterface2 call is missing pre-1.11). While submitting that fix, I missed a couple of places (sigh), and also the fact that Interface.EmbeddedType was new as well. Finally, some of the new tests don't pass at all pre-1.11 due to larger fixes in go/types. I've split up the code into version-tagged files and I believe it works now. The primary reason for having these problems in the first place (and not fixing it all with a single CL) is that I relied on the builders to test non-1.11 versions for "expediency" (I hoped to get around installing a pre-1.11 setup on my new laptop while on the go.) Lesson (re-)learned.

I still see a build failure for 1.9 but it is unrelated to the importers.

Please confirm this is now working again and close if so. Thanks.

**Comment by Tkanos** [comment]
Hello @griesemer,
Next time, to do all your changes with calm, 
Isn't it better to revert the changes that cause the issue, instead trying to resolve them on the hurry (that shouldn't be comfortable for you).

Good point of the adventure : Now all gophers know your name :D

**Comment by dominikh** [comment]
> Now all gophers know your name

All decent gophers should've already known his name :-)

**Comment by griesemer** [comment]
Hi @Tkanos, you're absolutely right, of course.

**Comment by iwanbk** [comment]
hi @griesemer 

i still got this error with Go 1.10.8
```
$ go version
go version go1.10.8 darwin/amd64
```

```
$ go get -u golang.org/x/lint/golint
# golang.org/x/tools/go/internal/gcimporter
../../../golang.org/x/tools/go/internal/gcimporter/gcimporter.go:699:9: undefined: types.NewInterfaceType
```

**Comment by olivertang** [comment]
same issue, getting 

```
$ go get -u golang.org/x/lint/golint
# golang.org/x/tools/go/internal/gcimporter
../../../golang.org/x/tools/go/internal/gcimporter/gcimporter.go:699:9: undefined: types.NewInterfaceType
```

can someone please help?

**Comment by griesemer** [comment]
It looks like golint is using an old version of `x/tools/go/internal/gcimporter`. The current version supports both 1.10 and newer.

**Comment by andybons** [comment]
Making a CL...

**Comment by iwanbk** [comment]
thanks, works for Go 1.10 now
