### ISSUE TITLE
Unable to go get for go1.5 and fedora 23 linux

### ISSUE THREAD

**Issue by vodolaz095** [golang/lint#246]
```
go get -u github.com/golang/lint/golint
# github.com/golang/lint
../../../github.com/golang/lint/lint.go:250: undefined: types.ImportMode
```

The head of my local code is on 64229b89515c2a585c623c79a7ccdea71e8589ff

**Comment by dsnet** [comment]
What version of Go are you using? We recently dropped support for Go 1.5 to clean up the code a little. It should work for Go 1.6 and up.

**Comment by vodolaz095** [comment]
the stack version from my favourite Fedora 24 linux(
```
[vodolaz095@steel ~]$ go version
go version go1.5.4 linux/amd64
```

**Comment by dsnet** [comment]
That explains it. Are you able to upgrade to a newer version of Go? I'd rather not revert the change and support Go1.5 again.

**Comment by vodolaz095** [comment]
oh, it looks like upgrading is not so trivial. 
i still have 23 version of Fedora linux and it has go 1.5

What latest revision of golint do works on Go 1.5.x?

**Comment by dsnet** [comment]
You can try c6242afa6ced3be489e1184eb80bc2d85f1f5e7b.

**Comment by vodolaz095** [comment]
thanks

**Comment by ramya-rao-a** [comment]
@dsnet Can we have a branch/tag that supports go 1.5.x ? This branch need not have any changes that you do in the master branch change post https://github.com/golang/lint/commit/a428635c58fe96360e83667e2e1a8343fc292bf0 

This way, people who are still on Go 1.5.x can use [gopkg.in](http://labix.org/gopkg.in) to get a working version of golint
