### ISSUE TITLE
x/lint: no longer builds on Go 1.6

### ISSUE THREAD

**Issue by LawnGnome** [golang/lint#400]
The fix for https://github.com/golang/go/issues/25052 has made it impossible to `go get -u golang.org/x/lint/golint` on Go 1.6, as the backported `iimport.go` file relies on Go 1.7 features:

```
root@84d63d240f46:/go# go version
go version go1.6.4 linux/amd64
root@84d63d240f46:/go# go get -u golang.org/x/lint/golint
# golang.org/x/tools/go/internal/gcimporter
src/golang.org/x/tools/go/internal/gcimporter/iimport.go:77: undefined: io.SeekCurrent
src/golang.org/x/tools/go/internal/gcimporter/iimport.go:80: undefined: io.SeekCurrent
src/golang.org/x/tools/go/internal/gcimporter/iimport.go:156: undefined: io.SeekCurrent
src/golang.org/x/tools/go/internal/gcimporter/iimport.go:187: r.declReader.Reset undefined (type bytes.Reader has no field or method Reset)
src/golang.org/x/tools/go/internal/gcimporter/iimport.go:226: r.declReader.Reset undefined (type bytes.Reader has no field or method Reset)
```

My understanding from [the review for that fix](https://go-review.googlesource.com/c/tools/+/109595#message-a1aa43660b13e1102d1265cd5e1b3c8ee4295d93) is that only tip - 2 versions is supported by `x/tools`, so I'm unsure where to open this bug. Given that it feels like it might not be fixed in the downstream dependency, I'm opening the issue here for now in case the fix is to change the minimum version lint supports.

**Comment by ianlancetaylor** [comment]
The general guideline that we only support two previous releases applies to all the golang.org/x repos, including golang.org/x/lint.  Basically, it seems unreasonable to require the golang.org/x code to work for all old Go releases, so we have to draw the line somewhere.

**Comment by andybons** [comment]
Ian is correct. We're sorry but as Ian said, we have to draw the line somewhere.

Also, unless this is part of a test to check for backward compatibility with 1.6 (or something similar), I strongly suggest you update your environment since you run the risk of exposing yourself to security vulnerabilities that have been fixed since 1.6.

**Comment by LawnGnome** [comment]
> The general guideline that we only support two previous releases applies to all the golang.org/x repos, including golang.org/x/lint.

That's totally fine, but the README does explicitly include the following right now:

>Golint requires Go 1.6 or later.

Would you like a PR to update that?

**Comment by andybons** [comment]
Yes that would be great. Thank you.
